export const environment = {
  production: true,
  firebase: {
    apiKey: 'AIzaSyCww3we6VOn2RpHFYGIsxYAtn7iQwQb6EE',
    authDomain: 'extinctathon-backend.firebaseapp.com',
    databaseURL: 'https://extinctathon-backend.firebaseio.com',
    projectId: 'extinctathon-backend',
    storageBucket: 'extinctathon-backend.appspot.com',
    messagingSenderId: '477523141034'
  },
  animals: [
    'Atlas wild ass', 'Canary Islands giant rat', 'Giant aye-aye', 'Giant fossa', 'Koala lemur', 'Lava mouse', 'Bibymalagasy',
    'Malagasy hippopotamus', 'North African elephant', 'Atlas bear', 'Aurochs', 'Bluebuck', 'Bubal hartebeest', 'Cape lion',
    'Cape serval', 'Cape warthog', 'Kenya oribi', 'Large sloth lemur', 'Lesser Mascarene flying fox', 'Quagga', 'Red gazelle',
    'Robert\'s lechwe', 'Western black rhinoceros', 'De Winton\'s golden mole', 'Ethiopian amphibious rat', 'Wimmer\'s shrew',
    'Alaotra grebe', 'Aldabra brush-warbler', 'Ascension flightless crake', 'Ascension night heron', 'Broad-billed parrot',
    'Canary Islands oystercatcher', 'Canary Islands quail', 'Delalande\'s coua', 'Dodo', 'Eastern Canary Islands chiffchaff',
    'Elephant bird', 'Lagrand\'s ground roller', 'Large Saint Helena petrel', 'Madeiran wood pigeon',
    'Mascarene coot', 'Mascarene grey parakeet', 'Mascarene parrot', 'Mauritian duck', 'Mauritian shelduck',
    'Mauritius blue pigeon', 'Mauritius grey parrot', 'Mauritius night-heron', 'Mauritius owl', 'Mauritius starling', 'Newton\'s parakeet',
    'Red rail', 'Réunion flightless ibis', 'Réunion gallinule', 'Réunion kestrel', 'Réunion night-heron', 'Réunion owl', 'Réunion pigeon',
    'Réunion shelduck', 'Réunion starling', 'Rodrigues night-heron', 'Rodrigues owl', 'Rodrigues parrot', 'Rodrigues rail',
    'Rodrigues solitaire', 'Rodrigues starling', 'Saint Helena crake', 'Saint Helena cuckoo', 'Saint Helena dove', 'Saint Helena hoopoe',
    'Saint Helena rail', 'Seychelles parakeet', 'Small Saint Helena petrel', 'Tristan moorhen', 'Cape Verde giant skink',
    'Domed Mauritius giant tortoise', 'Domed Rodrigues giant tortoise', 'Eastwood\'s long-tailed seps', 'Hoffstetter\'s worm snake',
    'Mauritian giant skink', 'Mozambique centipede-eater', 'Réunion giant tortoise', 'Rodrigues day gecko', 'Rodrigues giant day gecko',
    'Roque Chico de Salmor giant lizard', 'Round Island burrowing boa', 'Saddle-backed Mauritius giant tortoise',
    'Saddle-backed Rodrigues giant tortoise', 'Du Toit\'s torrent frog', 'Osgood\'s Ethiopian toad', 'Togo slippery frog', 'Cave lion',
    'Chinese elephant', 'Cyprus dwarf hippopotamus', 'Giant tapir', 'Giant Deer', 'Steppe wisent', 'Syrian elephant', 'Woolly mammoth',
    'Woolly rhinoceros', 'Aurochs', 'Bali tiger', 'Buhler\'s coryphomys', 'Caspian tiger', 'Caucasian moose', 'Caucasian wisent',
    'Cebu warty pig', 'Flores cave rat', 'Flores long-nosed rat', 'Formosan clouded leopard', 'Hokkaidō wolf', 'Honshū wolf',
    'Ilin Island cloudrunner', 'Indian Javan rhinoceros', 'Japanese river otter', 'Japanese sea lion', 'Javan tiger',
    'Northern Sumatran rhinoceros', 'Queen of Sheba\'s gazelle', 'Saudi gazelle', 'Schomburgk\'s deer', 'Steller\'s sea cow',
    'Sturdee\'s pipistrelle', 'Verhoeven\'s giant tree rat', 'Vietnamese Javan rhinoceros', 'Baiji', 'Gloomy tube-nosed bat', 'Kouprey',
    'Malabar civet', 'Arabian ostrich', 'Asian ostrich', 'Bering cackling goose', 'Bonin grosbeak', 'Bonin nankeen night heron',
    'Bonin thrush', 'Bonin wood pigeon', 'Bennu heron', 'Cebu hanging parrot', 'Cyprus dipper', 'Mukojima white-eye', 'Ryukyu kingfisher',
    'Ryukyu wood pigeon', 'Spectacled cormorant', 'Black-browed babbler', 'Catanduanes bleeding heart', 'Crested shelduck',
    'Himalayan quail', 'Javan lapwing', 'Negros fruit dove', 'Pink-headed duck', 'Rück\'s blue flycatcher', 'Siau scops owl',
    'Slender-billed curlew', 'Sulu bleeding-heart', 'Vaurie\'s nightjar', 'White-eyed river martin', 'Gunther\'s streamlined frog',
    'Yunnan lake newt', 'Balearic giant shrew', 'Balearic Islands cave goat', 'Canary Islands giant rats', 'Cave bear', 'Cave hyena',
    'Panthera spelaea', 'Cretan dwarf megacerine', 'Cretan dwarf hippopotamus', 'Dwarf elephant', 'European ass', 'Irish elk',
    'Majorcan giant dormouse', 'Maltese hippopotamus', 'Minorcan giant dormouse', 'Sardinian dhole', 'Woolly mammoth', 'Woolly rhinoceros',
    'Giant swan', 'Ibizan rail', 'Aurochs', 'Caspian tiger', 'Caucasian elk', 'Caucasian wisent', 'Carpathian wisent', 'Lion',
    'Majorcan hare', 'Portuguese ibex', 'Pyrenean ibex', 'Sardinian giant shrew', 'Sardinian lynx', 'Sardinian pika',
    'St. Kilda house mouse', 'Tarpan', 'Great auk', 'Pied raven', 'Ratas Island lizard', 'Roque Chico de Salmor giant lizard',
    'Santo Stefano lizard', 'Gravenche', 'Houting', 'Lake Constance whitefish', 'Techirghiol stickleback', 'Ukrainian migratory lamprey',
    'Madeiran large white', 'British large copper', 'Silver-studded blue subsp. masseyi', 'Scarce large blue subsp. burdigalensis',
    'Perrin\'s cave beetle', 'Tobias\' caddisfly', 'Ivell\'s sea anemone"', 'American mastodon', 'American mountain deer',
    'Beautiful armadillo', 'Caribbean ground sloths', 'Columbian mammoth', 'Dire wolf', 'Florida spectacled bear', 'Harlan\'s muskox',
    'Jefferson\'s ground sloth', 'Pleistocene North American jaguar', 'Pygmy mammoth', 'Saber-toothed cat', 'Saiga antelope',
    'Scimitar-toothed cats', 'Giant short-faced bear', 'Shrub-ox', 'Western horse', 'Woolly mammoth', 'Martinique giant rice rat',
    'Anthony\'s woodrat', 'Banks Island wolf', 'Barbados raccoon', 'Bunker\'s woodrat', 'California grizzly bear', 'Caribbean monk seal',
    'Cascade Mountains wolf', 'Cuban coney', 'Eastern cougar', 'Eastern elk', 'Goff\'s pocket gopher', 'Gull Island vole',
    'Hispaniolan edible rat', 'Insular cave rat', 'Imposter hutia', 'Jamaican monkey', 'Jamaican rice rat', 'Little Swan Island hutia',
    'Marcano\'s solenodon', 'Merriam\'s elk', 'Mexican grizzly bear', 'Montane hutia', 'Nelson\'s rice rat', 'Nevis rice rat',
    'Newfoundland wolf', 'Oriente cave rat', 'Pallid beach mouse', 'Puerto Rican hutia', 'Puerto Rican long-nosed bat',
    'Saint Lucia giant rice rat', 'Saint Vincent pygmy rice rat', 'Samana hutia', 'San Martín Island woodrat', 'Sea mink',
    'Smith Island cottontail', 'Southern California kit fox', 'Southern Rocky Mountain wolf', 'Steller\'s sea cow', 'Tacoma pocket gopher',
    'Torre\'s cave rat', 'Tule shrew', 'West Indies nesophontes', 'Atalaye nesophontes', 'Cuban nesophontes', 'Greater Cuban nesophontes',
    'Haitian nesophontes', 'Lesser Cuban nesophontes', 'Puerto Rican nesophontes', 'Saint Michel nesophontes', 'Slender Cuban nesophontes',
    'Western Cuban nesophontes', 'Dwarf hutia', 'Garrido\'s hutia', 'Puebla deer mouse', 'San Quintin kangaroo rat', 'San Felipe hutia',
    'Sclater\'s shrew', 'Antillean cave rail', 'Californian turkey', 'Cuban condor', 'La Brea stork', 'Saint Croix macaw', 'Teratorns',
    'Woodward\'s eagle', 'Antiguan burrowing owl', 'Atitlán grebe', 'Bahaman barn owl', 'Bermuda flicker', 'Bermuda hawk',
    'Bermuda night heron', 'Bermuda saw-whet owl', 'Brace\'s emerald', 'Carolina parakeet', 'Cuban ivory-billed woodpecker',
    'Cuban macaw', 'Dusky seaside sparrow', 'Gould\'s emerald', 'Grand Cayman thrush', 'Great auk', 'Guadalupe caracara',
    'Guadeloupe burrowing owl', 'Guadeloupe parakeet', 'Guadeloupe parrot', 'Heath hen', 'Labrador duck', 'Lesser Antillean macaw',
    'Martinique parrot', 'Mauge\'s parakeet', 'New Mexico sharp-tailed grouse', 'Passenger pigeon', 'Slender-billed grackle',
    'Spectacled cormorant', 'Socorro elf owl', 'Bachman\'s warbler', 'Eskimo curlew', 'Guadalupe storm-petrel', 'Imperial woodpecker',
    'Indigo-capped hummingbird', 'American ivory-billed woodpecker', 'Jamaican petrel', 'Jamaican poorwill', 'Semper\'s warbler',
    'Martinique giant ameiva', 'Martinique curly-tailed lizard', 'Navassa curly-tailed lizard', 'Guadeloupe ameiva',
    'Navassa Island dwarf boa', 'Navassa Island iguana', 'Saint Croix racer', 'Culebra Island giant anole', 'Jamaica giant galliwasp',
    'Ainsworth\'s salamander', 'Golden toad', 'Rabbs\' fringe-limbed treefrog', 'Atoyac minute salamander', 'Bigfoot splayfoot salamander',
    'Golden coqui', 'San Martin pygmy salamander', 'Web-footed coquí', 'Saber-toothed salmon', 'Alberca silverside',
    'Alvord cutthroat trout', 'Amistad gambusia', 'Ash Meadows killifish', 'Banff longnose dace', 'Blackfin cisco', 'Blue walleye',
    'Cachorrito de la Trinidad', 'Catarina pupfish', 'Clear Lake splittail', 'Deepwater cisco', 'Durango shiner', 'Endorheic chub',
    'Graceful priapella', 'Grass Valley speckled dace', 'Harelip sucker', 'Las Vegas dace', 'Least silverside', 'Longjaw cisco',
    'Maryland darter', 'Mexican dace', 'Pahranagat spinedace', 'Phantom shiner', 'Parras characodon', 'Perrito de Parras',
    'Perrito de Sandia', 'Plateau chub', 'Raycraft Ranch killifish', 'Rio Grande bluntnose shiner', 'Salado shiner', 'San Marcos gambusia',
    'Scioto madtom', 'Shortnose cisco', 'Silver trout', 'Snake River sucker', 'Stumptooth minnow', 'Tecopa pupfish', 'Thicktail chub',
    'Utah Lake sculpin', 'Villa Lopez pupfish', 'Yellowfin cutthroat trout', 'Emperor rat', 'Guadalcanal rat', 'Guam flying fox',
    'Large Palau flying fox', 'Nendo tube-nosed fruit bat', 'Aru flying fox', 'Emma\'s giant rat', 'New Guinea big-eared bat',
    'Telefomin cuscus', 'Vanikoro flying fox', 'Wondiwoi tree-kangaroo', 'Bar-winged rail', 'Bay thrush', 'Black-fronted parakeet',
    'Choiseul pigeon', 'Consumed scrubfowl', 'Eiao monarch', 'Guam flycatcher', 'Kosrae crake', 'Kosrae starling', 'Liverpool pigeon',
    'Makira woodhen', 'Mariana mallard', 'Marquesas swamphen', 'Maupiti monarch', 'Miller\'s rail', 'Mysterious starling',
    'New Caledonian gallinule', 'New Caledonian giant scrubfowl', 'Noble megapode', 'Nuku Hiva monarch', 'Oceanic eclectus parrot',
    'Pile-builder megapode', 'Red-moustached fruit dove', 'Society parakeet', 'Tahitian red-billed rail', 'Tahiti sandpiper',
    'Moorea sandpiper', 'Kiritimati sandpiper', 'Tanna ground dove', 'Thick-billed ground dove', 'Tongatapu rail', 'Viti Levu scrubfowl',
    'Wake Island rail', 'White-winged sandpiper', 'New Caledonian lorikeet', 'New Caledonian rail', 'Pohnpei starling', 'Samoan wood rail',
    'Ua Pou monarch', 'Tonga ground skink', 'Volia', 'Meiolania', 'Levuana moth', 'Mount Matafao different snail', 'Mount Alifana partula',
    'Dire wolf', 'Ground sloths', 'Glyptodonts', 'Stout-legged llama', 'Candango mouse', 'Caribbean monk seal', 'Darwin\'s Galapagos mouse',
    'Falkland Islands wolf', 'Galápagos giant rat', 'Indefatigable Galapagos mouse', 'Giant vampire bat', 'Peruvian viscacha',
    'Red-bellied gracile opossum', 'Vespucci\'s rodent', 'One-striped opossum', 'Pacific degu', 'Zuniga\'s dark rice rat',
    'Alejandro Selkirk Island firecrown', 'Colombian grebe', 'Darwin\'s ground finch', 'Niceforo\'s pintail',
    'San Cristóbal vermilion flycatcher', 'Red-throated wood-rail', 'Antioquia brush finch', 'Bogota sunangel', 'Northern curlew',
    'Glaucous macaw', 'Hooded seedeater', 'Letitia\'s thorntail', 'Turquoise-throated puffleg', 'Spiny-knee leaf frog',
    'Chile Darwin\'s frog', 'Charles Island tortoise', 'Pinta Island tortoise', 'Greasefish', 'Titicaca orestias'
  ]
};
